environment:
  matrix:
  - CYGWINSETUP: "http://cygwin.com/setup-x86.exe"
  - CYGWINSETUP: "http://cygwin.com/setup-x86_64.exe"

init:
# Carriage returns are bad
  - git config --global core.autocrlf input

install:
  - mkdir C:\cygwin
  - ps: (new-object net.webclient).DownloadFile($env:CYGWINSETUP, "C:\cygwin\setup.exe")
#  - C:\cygwin\setup.exe -q -n
  - C:\cygwin\setup.exe -q -n -g -P cygport
  - C:\cygwin\setup.exe -q -n -g -P python
  - C:\cygwin\setup.exe -q -n -g -P python-imaging
  - C:\cygwin\setup.exe -q -n -g -P python-pygments
  - C:\cygwin\setup.exe -q -n -g -P python-setuptools

build_script:
  - C:\cygwin\bin\sh -lc "uname -a;
      cygport --version;
      cd /cygdrive/c/projects/cygwin-python-sphinx;
      cygport python-sphinx.cygport download;
      cygport python-sphinx.cygport all"

artifacts:
  - path: 'python-sphinx-*\dist\python-sphinx\*'
