environment:
  matrix:
  - CYGWINSETUP: "http://cygwin.com/setup-x86.exe"
  - CYGWINSETUP: "http://cygwin.com/setup-x86_64.exe"

init:
# Carriage returns are bad
  - git config --global core.autocrlf input

install:
  - mkdir C:\cygwin
  - ps: (new-object net.webclient).DownloadFile($env:CYGWINSETUP, "C:\cygwin\setup.exe")
  - ps: foreach ($pkg in @("cygport","python","python-imaging","python-pygments","python-setuptools")) {
          Write-Host $("Installing "+$pkg);
          & C:/cygwin/setup.exe -q -n -g -P $pkg >$null 2>&1
        }

build_script:
  - C:\cygwin\bin\sh -lc "uname -a;
      cygport --version;
      cd /cygdrive/c/projects/cygwin-python-sphinx;
      cygport python-sphinx.cygport download;
      cygport python-sphinx.cygport all"

artifacts:
  - path: 'python-sphinx-*\dist\python-sphinx\*'
