environment:
  matrix:
  - SETUP: "setup-x86.exe"
  - SETUP: "setup-x86_64.exe"

init:
# Carriage returns are bad
  - git config --global core.autocrlf input

install:
  - ps: (new-object net.webclient).DownloadFile($("http://cygwin.com/"+$env:SETUP), $("C:\\cygwin\\"+$env:SETUP))
  - ps: foreach ($pkg in @("cygport","python","python-imaging","python-pygments","python-setuptools")) {
          Write-Host $("Installing "+$pkg)
          & $("C:\\cygwin\\"+$env:SETUP) -q -n -g -P $pkg >$null 2>&1
        }

build_script:
  - C:\cygwin\bin\sh -lc "uname -a;
      cygport --version;
      cd /cygdrive/c/projects/cygwin-python-sphinx;
      cygport python-sphinx.cygport download;
      cygport python-sphinx.cygport all"

artifacts:
  - path: 'python-sphinx-*\dist\python-sphinx\*'
